CREATE TABLE tb_unidade_medida(
 id BIGSERIAL PRIMARY KEY,
 nome VARCHAR(100) NOT NULL UNIQUE,
 sigla VARCHAR(10) NOT NULL UNIQUE,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 data_atualizacao TIMESTAMP
);

CREATE TABLE tb_categoria(
 id BIGSERIAL PRIMARY KEY,
 nome VARCHAR(100) NOT NULL UNIQUE,
 ativo BOOLEAN NOT NULL DEFAULT TRUE,
 data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 data_atualizacao TIMESTAMP
);