CREATE TABLE tb_fornecedor(
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(150) NOT NULL UNIQUE,
  cnpj VARCHAR(18) NOT NULL UNIQUE,
  telefone VARCHAR(20) NOT NULL,
  email VARCHAR(150) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP
);