spring.application.name=API-erp
spring.datasource.url=jdbc:postgresql://localhost:5439/erp_estoque
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate

# spring.flyway.enabled=true